[package]
name = "goldenrod"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["gui", "audio", "vst", "lv2"]
categories = ["gui", "visualization"]
description = "A simple GUI library for audio plugins"
homepage = "https://github.com/BillyDM/goldenrod"
documentation = "https://docs.rs/goldenrod"
repository = "https://github.com/BillyDM/goldenrod"
readme = "README.md"

[workspace]
members = [
    "examples/petal_drive"
]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["font-fallback", "gl-renderer"]
font-fallback = []
gl-renderer = ["surfman", "gl32"]
textures = ["image"]

[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", branch = "master" }
raw-window-handle = "0.3.3"
image = { version = "0.23", optional = true }
surfman = { version = "0.3.0", default-features = false, features = ["sm-raw-window-handle", "sm-wayland-default", "sm-x11"], optional = true }
gl32 = { version = "0.2.0", optional = true }