[package]
name = "goldenrod"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@protonmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["gui", "audio", "vst", "lv2"]
categories = ["gui", "visualization"]
description = "A simple GUI library for audio plugins"
homepage = "https://github.com/BillyDM/goldenrod"
documentation = "https://docs.rs/goldenrod"
repository = "https://github.com/BillyDM/goldenrod"
readme = "README.md"

[workspace]
members = [
    "examples/petal_drive"
]

[badges]
maintenance = { status = "actively-developed" }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["font-fallback"]
font-fallback = []

[dependencies]
baseview = { git = "https://github.com/RustAudio/baseview.git", branch = "master" }
wgpu = "0.6"
wgpu_glyph = "0.10"
zerocopy = "0.3"
image = "0.23"
fnv = "1.0.7"
anyhow = "1.0"
futures = "0.3"
raw-window-handle = "0.3"
guillotiere = "0.6.0"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"
shaderc = "0.6"